library_books = [
    {
        "id": "B1",
        "title": "The Lightning Thief",
        "author": "Rick Riordan",
        "genre": "Fantasy",
        "available": True,
        "due_date": None,
        "checkouts": 2
    },
    {
        "id": "B2",
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "genre": "Historical",
        "available": False,
        "due_date": "2025-11-01",
        "checkouts": 5
    },
    {
        "id": "B3",
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "genre": "Classic",
        "available": True,
        "due_date": None,
        "checkouts": 3
    }
,
    {   'author': 'George Orwell',
    'available': True,
    'checkouts': 4,
    'due_date': None,
    'genre': 'Dystopian',
    'id': 'B4',
    'title': '1984'},
    {   'author': 'Jane Austen',
    'available': True,
    'checkouts': 6,
    'due_date': None,
    'genre': 'Romance',
    'id': 'B5',
    'title': 'Pride and Prejudice'},
    {   'author': 'J.R.R. Tolkien',
    'available': False,
    'checkouts': 8,
    'due_date': '2025-11-10',
    'genre': 'Fantasy',
    'id': 'B6',
    'title': 'The Hobbit'},
    {   'author': 'Ray Bradbury',
    'available': True,
    'checkouts': 1,
    'due_date': None,
    'genre': 'Science Fiction',
    'id': 'B7',
    'title': 'Fahrenheit 451'},
    {   'author': 'J.D. Salinger',
    'available': False,
    'checkouts': 3,
    'due_date': '2025-11-12',
    'genre': 'Coming-of-Age',
    'id': 'B8',
    'title': 'The Catcher in the Rye'}
]
